@startuml simple-swimlane
!theme materia

title B端软件需求工程活动流程 - AI赋能全景图

start

|市场分析阶段|
:市场调研;
:商业机会识别;

|业务建模阶段|
:业务现状分析;
:核心业务流程分析;
:生成用户故事清单;

|业务需求阶段|
:确认产品目标;
:定义项目范围;
:业务需求确认;

|用户需求阶段|
:用户分类;
:确定用户代表;
:确定决策过程;
:需求调研执行;
:生成用户需求说明书;

|软件需求开发|
:需求开发;
:功能需求定义;
:非功能需求定义;
:需求冲突检测;
:需求评审;
:需求基线确立;

:需求交付;

stop

@enduml
